### ISSUE TITLE
update themes

### ISSUE THREAD

**Issue by tomazzz369** [Acemad/CobaltTheme#1]
menu and submenu (more) need a little update/resize

menu must be a little wider
https://user-images.githubusercontent.com/2512915/32146582-680e4324-bcd1-11e7-894d-fd14ccdaf54b.JPG

submenu more - menu is too short - open decrypted is outside menu

regards

**Comment by Acemad** [comment]
Okay, thanks for reporting, I'm gonna fix this !

**Comment by Acemad** [comment]
Fixed for Electron Themes.
